import { collection, doc, getDoc, getDocs, query, where, setDoc, runTransaction, serverTimestamp, deleteDoc, orderBy, limit } from 'firebase/firestore';
import type { User } from 'firebase/auth';
import { firestore } from './config';
import type { UserProfile, Progress, Journal, Lesson, Project, Experiment, Question } from '@/types';
import { lessons } from '@/data/lessons';
import { projects } from '@/data/projects';
import { experiments } from '@/data/experiments';
import { elements } from '@/data/elements';

function dbRequired(){const db=firestore();if(!db)throw new Error('Firebase бапталмаған.');return db;}
const now=()=>new Date().toISOString();
const studyDay=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Almaty',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export async function ensureProfile(user:User,extra?:{fullName?:string;grade?:number}){const db=dbRequired(),ref=doc(db,'users',user.uid);return runTransaction(db,async tx=>{const snap=await tx.get(ref);if(snap.exists()){const profile=snap.data() as UserProfile;if(extra){const updated={...profile,fullName:extra.fullName||profile.fullName,grade:extra.grade||profile.grade,updatedAt:now()};tx.set(ref,updated);return updated;}return profile;}const profile:UserProfile={uid:user.uid,fullName:extra?.fullName||user.displayName||user.email?.split('@')[0]||'Оқушы',email:user.email||'',photoURL:user.photoURL||'',role:'student',grade:extra?.grade||null,xp:0,streak:0,lastStudyDate:'',createdAt:now(),updatedAt:now()};tx.set(ref,profile);return profile;});}
export async function profileFor(uid:string){const snap=await getDoc(doc(dbRequired(),'users',uid));return snap.exists()?snap.data() as UserProfile:null;}
export async function updateOwnProfile(uid:string,patch:Pick<UserProfile,'fullName'|'grade'>){await setDoc(doc(dbRequired(),'users',uid),{...patch,updatedAt:now()},{merge:true});}

async function catalog<T extends {id:string;published:boolean}>(name:string,fallback:T[]):Promise<T[]>{const db=firestore();if(!db)return fallback;try{const [snap,states]=await Promise.all([getDocs(query(collection(db,name),where('published','==',true))),getDocs(collection(db,'catalogState'))]);const remote=snap.docs.map(d=>({...(d.data() as T),id:d.id})).filter(x=>!(x as T&{deleted?:boolean}).deleted);const ids=new Set(remote.map(x=>x.id));const hidden=new Set(states.docs.filter(d=>d.id.startsWith(`${name}_`)&&d.data().visible===false).map(d=>d.id.slice(name.length+1)));return [...remote,...fallback.filter(x=>!ids.has(x.id)&&!hidden.has(x.id))];}catch{return fallback;}}
export const getLessons=()=>catalog<Lesson>('lessons',lessons);
export const getProjects=()=>catalog<Project>('projects',projects);
export const getExperiments=()=>catalog<Experiment>('experiments',experiments);
export async function getElements(){const db=firestore();if(!db)return elements;try{const snap=await getDocs(collection(db,'elements'));if(snap.empty)return elements;const remote=snap.docs.map(d=>d.data() as typeof elements[number]);const ids=new Set(remote.map(x=>x.atomicNumber));return [...remote,...elements.filter(x=>!ids.has(x.atomicNumber))].sort((a,b)=>a.atomicNumber-b.atomicNumber);}catch{return elements;}}
export async function getLesson(slug:string){const all=await getLessons();const lesson=all.find(x=>x.slug===slug);if(!lesson)return null;const db=firestore();if(!db)return lesson;try{const snap=await getDocs(collection(db,'lessons',lesson.id,'questions'));if(snap.empty)return lesson;return {...lesson,questions:snap.docs.map(d=>({...(d.data() as Question),id:d.id})).sort((a,b)=>a.orderIndex-b.orderIndex)};}catch{return lesson;}}

export async function getProgress(uid:string){const snap=await getDocs(collection(dbRequired(),'users',uid,'progress'));return snap.docs.map(d=>d.data() as Progress);}
export async function startLesson(uid:string,lessonId:string){const db=dbRequired(),ref=doc(db,'users',uid,'progress',lessonId);await runTransaction(db,async tx=>{const s=await tx.get(ref);if(!s.exists())tx.set(ref,{lessonId,progress:10,score:0,correctAnswers:0,totalQuestions:5,completed:false,xpEarned:0,startedAt:now(),completedAt:null,updatedAt:now()} satisfies Progress);});await unlock(uid,'first-start','Алғашқы қадам');}
export async function saveQuiz(uid:string,lessonId:string,correct:number,total:number){const db=dbRequired(),ref=doc(db,'users',uid,'progress',lessonId),userRef=doc(db,'users',uid);const score=Math.round(correct/total*100);await runTransaction(db,async tx=>{const [old,user]=await Promise.all([tx.get(ref),tx.get(userRef)]);if(!user.exists())throw new Error('Профиль табылмады.');const data=old.exists()?old.data() as Progress:null;const previousQuizXp=Math.min(data?.correctAnswers||0,5)*10;const newQuizXp=Math.max(previousQuizXp,correct*10);const delta=newQuizXp-previousQuizXp;tx.set(ref,{lessonId,progress:data?.completed?100:Math.max(data?.progress||10,70),score:Math.max(data?.score||0,score),correctAnswers:Math.max(data?.correctAnswers||0,correct),totalQuestions:total,completed:data?.completed||false,xpEarned:(data?.completed?50:0)+newQuizXp,startedAt:data?.startedAt||now(),completedAt:data?.completedAt||null,updatedAt:now()} satisfies Progress);if(delta)tx.update(userRef,{xp:(user.data().xp||0)+delta,updatedAt:now()});});if(lessonId==='atom-kurylysy'&&score>=80)await unlock(uid,'atom-expert','Атом білгірі');return {score,xp:Math.max(0,correct*10)};}
export async function completeLesson(uid:string,lessonId:string){const db=dbRequired(),ref=doc(db,'users',uid,'progress',lessonId),userRef=doc(db,'users',uid);await runTransaction(db,async tx=>{const [old,user]=await Promise.all([tx.get(ref),tx.get(userRef)]);if(!user.exists())throw new Error('Профиль табылмады.');const data=old.exists()?old.data() as Progress:null;tx.set(ref,{lessonId,progress:100,score:data?.score||0,correctAnswers:data?.correctAnswers||0,totalQuestions:data?.totalQuestions||5,completed:true,xpEarned:(data?.xpEarned||0)+(data?.completed?0:50),startedAt:data?.startedAt||now(),completedAt:data?.completedAt||now(),updatedAt:now()} satisfies Progress);if(!data?.completed){const today=studyDay(),previous=user.data().lastStudyDate as string|undefined,yesterday=new Date(`${today}T00:00:00Z`);yesterday.setUTCDate(yesterday.getUTCDate()-1);const streak=previous===today?(user.data().streak||1):previous===yesterday.toISOString().slice(0,10)?(user.data().streak||0)+1:1;tx.update(userRef,{xp:(user.data().xp||0)+50,streak,lastStudyDate:today,updatedAt:now()});}});await unlock(uid,'first-complete','Жас зерттеуші');if(lessonId==='himiyalyk-reaktsiyalar')await unlock(uid,'reaction-master','Реакция шебері');if(lessonId==='ekologiyalyk-himiya')await unlock(uid,'green-chemist','Жасыл химик');}
export async function unlock(uid:string,id:string,title:string){const db=dbRequired(),ref=doc(db,'users',uid,'achievements',id);await runTransaction(db,async tx=>{if(!(await tx.get(ref)).exists())tx.set(ref,{achievementId:id,title,unlockedAt:now()});});}
export async function getAchievements(uid:string){const s=await getDocs(collection(dbRequired(),'users',uid,'achievements'));return s.docs.map(d=>d.id);}
export async function saveExperiment(uid:string,id:string){const db=dbRequired(),ref=doc(db,'users',uid,'experiments',id),userRef=doc(db,'users',uid);await runTransaction(db,async tx=>{const [old,user]=await Promise.all([tx.get(ref),tx.get(userRef)]);if(!user.exists())throw new Error('Профиль табылмады.');if(!old.exists()){tx.set(ref,{experimentId:id,completedAt:now()});tx.update(userRef,{xp:(user.data().xp||0)+30,updatedAt:now()});}});const done=await getDocs(collection(db,'users',uid,'experiments'));if(done.size>=3)await unlock(uid,'lab-expert','Зертхана сарапшысы');}
export async function getExperimentsDone(uid:string){const s=await getDocs(collection(dbRequired(),'users',uid,'experiments'));return s.docs.map(d=>d.id);}
export async function saveJournal(uid:string,entry:Journal){const db=dbRequired(),ref=doc(db,'users',uid,'researchJournal',entry.projectId),userRef=doc(db,'users',uid);await runTransaction(db,async tx=>{const [old,user]=await Promise.all([tx.get(ref),tx.get(userRef)]);if(!user.exists())throw new Error('Профиль табылмады.');tx.set(ref,{...entry,createdAt:old.exists()?old.data().createdAt:now(),updatedAt:now()});if(!old.exists())tx.update(userRef,{xp:(user.data().xp||0)+40,updatedAt:now()});});}
export async function getJournal(uid:string,id:string){const s=await getDoc(doc(dbRequired(),'users',uid,'researchJournal',id));return s.exists()?s.data() as Journal:null;}
export async function getJournals(uid:string){const s=await getDocs(collection(dbRequired(),'users',uid,'researchJournal'));return s.docs.map(d=>d.data() as Journal);}

export async function teacherData(){const db=dbRequired();const [usersSnap,lessonsSnap,projectsSnap,experimentsSnap,statesSnap]=await Promise.all([getDocs(query(collection(db,'users'),where('role','==','student'))),getDocs(collection(db,'lessons')),getDocs(collection(db,'projects')),getDocs(collection(db,'experiments')),getDocs(collection(db,'catalogState'))]);const hidden=new Set(statesSnap.docs.filter(d=>d.data().visible===false).map(d=>d.id));const remoteLessons=lessonsSnap.docs.map(d=>({...(d.data() as Lesson),id:d.id})),remoteProjects=projectsSnap.docs.map(d=>({...(d.data() as Project),id:d.id})),remoteExperiments=experimentsSnap.docs.map(d=>({...(d.data() as Experiment),id:d.id}));return {students:usersSnap.docs.map(d=>d.data() as UserProfile),lessons:[...remoteLessons.filter(x=>!((x as Lesson&{deleted?:boolean}).deleted)),...lessons.filter(x=>!remoteLessons.some(r=>r.id===x.id)&&!hidden.has(`lessons_${x.id}`))],projects:[...remoteProjects.filter(x=>!((x as Project&{deleted?:boolean}).deleted)),...projects.filter(x=>!remoteProjects.some(r=>r.id===x.id)&&!hidden.has(`projects_${x.id}`))],experiments:[...remoteExperiments.filter(x=>!((x as Experiment&{deleted?:boolean}).deleted)),...experiments.filter(x=>!remoteExperiments.some(r=>r.id===x.id)&&!hidden.has(`experiments_${x.id}`))]};}
export async function studentProgressForTeacher(uid:string){return getProgress(uid);}
async function visibility(name:string,id:string,visible:boolean){await setDoc(doc(dbRequired(),'catalogState',`${name}_${id}`),{visible,updatedAt:serverTimestamp()});}
export async function saveLesson(lesson:Lesson){const db=dbRequired();await setDoc(doc(db,'lessons',lesson.id),{...lesson,updatedAt:serverTimestamp()},{merge:true});await Promise.all(lesson.questions.map(q=>setDoc(doc(db,'lessons',lesson.id,'questions',q.id),q)));await visibility('lessons',lesson.id,lesson.published);}
export async function deleteLesson(id:string){const db=dbRequired();const qs=await getDocs(collection(db,'lessons',id,'questions'));await Promise.all(qs.docs.map(d=>deleteDoc(d.ref)));await setDoc(doc(db,'lessons',id),{published:false,deleted:true,updatedAt:serverTimestamp()},{merge:true});await visibility('lessons',id,false);}
export async function saveProject(project:Project){await setDoc(doc(dbRequired(),'projects',project.id),{...project,updatedAt:serverTimestamp()},{merge:true});await visibility('projects',project.id,project.published);}
export async function deleteProject(id:string){await setDoc(doc(dbRequired(),'projects',id),{published:false,deleted:true,updatedAt:serverTimestamp()},{merge:true});await visibility('projects',id,false);}
export async function saveExperimentCatalog(experiment:Experiment){await setDoc(doc(dbRequired(),'experiments',experiment.id),{...experiment,updatedAt:serverTimestamp()},{merge:true});await visibility('experiments',experiment.id,experiment.published);}
export async function deleteExperimentCatalog(id:string){await setDoc(doc(dbRequired(),'experiments',id),{published:false,deleted:true,updatedAt:serverTimestamp()},{merge:true});await visibility('experiments',id,false);}
export async function recentActivities(){const db=dbRequired();const s=await getDocs(query(collection(db,'users'),where('role','==','student'),orderBy('updatedAt','desc'),limit(6)));return s.docs.map(d=>d.data() as UserProfile);}
