export type Difficulty = 'Жеңіл' | 'Орташа' | 'Күрделі';
export interface Question { id:string; question:string; options:[string,string,string,string]; correctIndex:number; explanation:string; points:number; orderIndex:number }
export interface Lesson { id:string; slug:string; title:string; description:string; objective:string; grade:number; category:string; difficulty:Difficulty; duration:number; orderIndex:number; sections:{title:string;body:string}[]; concepts:string[]; formulas:string[]; equations:string[]; examples:string[]; fact:string; safety:string; matching:{term:string;definition:string}[]; questions:Question[]; homework:string; published:boolean; content?:string }
export interface Element { atomicNumber:number; symbol:string; name:string; atomicMass:string; category:string; group:number|null; period:number; electronConfiguration:string; description:string; usage:string; interestingFact:string; x:number; y:number }
export interface Experiment { id:string;slug:string;title:string;description:string;goal:string;reactants:string[];choices:string[];result:string;equation:string;explanation:string;safetyNotes:string;difficulty:Difficulty;published:boolean;color:string }
export interface Project { id:string;slug:string;title:string;description:string;relevance:string;goal:string;tasks:string[];researchQuestion:string;hypothesis:string;materials:string[];steps:string[];safetyNotes:string;conclusion:string;references:string[];tableHeaders:string[];difficulty:Difficulty;duration:string;grade:string;published:boolean }
export interface UserProfile {uid:string;fullName:string;email:string;photoURL:string;role:'student'|'teacher';grade:number|null;xp:number;streak:number;lastStudyDate?:string;createdAt:string;updatedAt:string}
export interface Progress {lessonId:string;progress:number;score:number;correctAnswers:number;totalQuestions:number;completed:boolean;xpEarned:number;startedAt:string;completedAt:string|null;updatedAt:string}
export interface Journal {projectId:string;hypothesis:string;observations:string;results:string;conclusion:string;createdAt:string;updatedAt:string}
